'use strict'

exports.name = 'CON'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'ConsentType'
  , 'ConsentFormIDAndVersion'
  , 'ConsentFormNumber'
  , 'ConsentText'
  , 'SubjectSpecificConsentText'
  , 'ConsentBackgroundInformation'
  , 'SubjectSpecificConsentBackgroundText'
  , 'ConsenterImposedLimitations'
  , 'ConsentMode'
  , 'ConsentStatus'
  , 'ConsentDiscussionDateTime'
  , 'ConsentDecisionDateTime'
  , 'ConsentEffectiveDateTime'
  , 'ConsentEndDateTime'
  , 'SubjectCompetenceIndicator'
  , 'TranslatorAssistanceIndicator'
  , 'LanguageTranslatedTo'
  , 'InformationalMaterialSuppliedIndicator'
  , 'ConsentBypassReason'
  , 'ConsentDisclosureLevel'
  , 'ConsentNonDisclosureReason'
  , 'NonSubjectConsenterReason'
  , 'ConsenterID'
  , 'RelationshipToSubject'
]
